services:
  dev:
    build:
      context: ../bridge
      dockerfile: Dockerfile
    image: wyze-bridge-dev:latest
    container_name: wyze-bridge2-dev
    platform: linux/arm64
    working_dir: /work
    volumes:
      - .:/work
      - ../bridge/libs:/work/libs:ro
      - ../apk:/apk:ro
    env_file:
      - .env
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
    command: /bin/bash
