[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
board_build.flash_mode = dio
